#!/bin/bash
if [ -n "$1" ]; then
    game=$1
    processing cli --sketch="$game" --run
else 
    echo "----- GAME LIBRARY -----"
    echo "To launch a game directly run \"$0 <game>\""
    echo "--- Menu ---"
    PS3="Choose Game: "
    games=("CaptainToadTowerClimb" "UNO" "RainbowRush" "FoxForest")
    select game in ${games[@]}; do
        processing cli --sketch="$game" --run
        break
    done
fi


