#!/bin/bash
if [ -n "$1" ]; then
    echo "HIHI"
    game=$1
    processing cli --sketch="$game" --run
else 
    PS3="Choose Game: "
    games=("CaptainToadTowerClimb" "UNO" "RainbowRush" "FoxForest")
    select game in ${games[@]}; do
        processing cli --sketch="$game" --run
        break
    done
fi


